const data = [
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Africa International University",
    "state-province": null,
    domains: ["aiu.ac.ke"],
    web_pages: ["http://www.aiu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Aga Khan University",
    "state-province": null,
    domains: ["aku.edu"],
    web_pages: ["http://www.aku.edu/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Africa Nazarene University",
    "state-province": null,
    domains: ["anu.ac.ke"],
    web_pages: ["http://www.anu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Adventist University of Africa",
    "state-province": null,
    domains: ["aua.ac.ke"],
    web_pages: ["http://www.aua.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Chuka University",
    "state-province": null,
    domains: ["chuka.ac.ke"],
    web_pages: ["http://www.chuka.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Catholic University of Eastern Africa",
    "state-province": null,
    domains: ["cuea.edu"],
    web_pages: ["http://www.cuea.edu/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Daystar University",
    "state-province": null,
    domains: ["daystar.ac.ke"],
    web_pages: ["http://www.daystar.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Dedan Kimathi University of Technology",
    "state-province": null,
    domains: ["dkut.ac.ke"],
    web_pages: ["http://www.dkut.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Egerton University",
    "state-province": null,
    domains: ["egerton.ac.ke"],
    web_pages: ["http://www.egerton.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Great Lakes University of Kisumu",
    "state-province": null,
    domains: ["gluk.ac.ke"],
    web_pages: ["http://www.gluk.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Gretsa Universtiy",
    "state-province": null,
    domains: ["gretsauniversity.ac.ke"],
    web_pages: ["http://www.gretsauniversity.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Inoorero University",
    "state-province": null,
    domains: ["iu.ac.ke"],
    web_pages: ["http://www.iu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Jomo Kenyatta University of Agriculture and Technology",
    "state-province": null,
    domains: ["jkuat.ac.ke"],
    web_pages: ["http://www.jkuat.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Jaramogi Oginga Odinga University of Science and Technology",
    "state-province": null,
    domains: ["jooust.ac.ke"],
    web_pages: ["http://www.jooust.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kabarak University",
    "state-province": null,
    domains: ["kabarak.ac.ke"],
    web_pages: ["http://www.kabarak.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "University of Kabianga",
    "state-province": null,
    domains: ["kabianga.ac.ke"],
    web_pages: ["http://www.kabianga.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Karatina University",
    "state-province": null,
    domains: ["karatinauniversity.ac.ke"],
    web_pages: ["http://www.karatinauniversity.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kenya College of Accountancy",
    "state-province": null,
    domains: ["kca.ac.ke"],
    web_pages: ["http://www.kca.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kenya Methodist University",
    "state-province": null,
    domains: ["kemu.ac.ke"],
    web_pages: ["http://www.kemu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kisii University",
    "state-province": null,
    domains: ["kisiiuniversity.ac.ke"],
    web_pages: ["http://www.kisiiuniversity.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kenya Medical Training College",
    "state-province": null,
    domains: ["kmtc.ac.ke"],
    web_pages: ["http://www.kmtc.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kenyatta University",
    "state-province": null,
    domains: ["ku.ac.ke"],
    web_pages: ["http://www.ku.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Kiriri Womens University of Science and Technology",
    "state-province": null,
    domains: ["kwust.ac.ke"],
    web_pages: ["http://www.kwust.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Laikipia University",
    "state-province": null,
    domains: ["laikipia.ac.ke"],
    web_pages: ["http://www.laikipia.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Maseno University",
    "state-province": null,
    domains: ["maseno.ac.ke"],
    web_pages: ["http://www.maseno.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Mount Kenya University",
    "state-province": null,
    domains: ["mku.ac.ke"],
    web_pages: ["http://www.mku.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Maasai Mara University",
    "state-province": null,
    domains: ["mmarau.ac.ke"],
    web_pages: ["http://www.mmarau.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Multimedia University of Kenya",
    "state-province": null,
    domains: ["mmu.ac.ke"],
    web_pages: ["http://www.mmu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Masinde Muliro University of Science and Technology",
    "state-province": null,
    domains: ["mmust.ac.ke"],
    web_pages: ["http://www.mmust.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Moi University",
    "state-province": null,
    domains: ["mu.ac.ke"],
    web_pages: ["http://www.mu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Meru University of Science and Technology",
    "state-province": null,
    domains: ["must.ac.ke"],
    web_pages: ["http://www.must.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Nairobi Institute of Business Studies",
    "state-province": null,
    domains: ["nibs.ac.ke"],
    web_pages: ["http://www.nibs.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Nairobi Technical Training Institute",
    "state-province": null,
    domains: ["ntti.ac.ke"],
    web_pages: ["http://www.ntti.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Pan Africa Christian University",
    "state-province": null,
    domains: ["pacuniversity.ac.ke"],
    web_pages: ["http://www.pacuniversity.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Pioneer International University",
    "state-province": null,
    domains: ["piu.ac.ke"],
    web_pages: ["http://www.piu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Pwani University",
    "state-province": null,
    domains: ["pu.ac.ke"],
    web_pages: ["http://www.pu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Presbyterian University of East Africa",
    "state-province": null,
    domains: ["puea.ac.ke"],
    web_pages: ["http://www.puea.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Riara University School of Business and Law",
    "state-province": null,
    domains: ["riarauniversity.ac.ke"],
    web_pages: ["http://www.riarauniversity.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Scott Christian University",
    "state-province": null,
    domains: ["scott.ac.ke"],
    web_pages: ["http://www.scott.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "South Eastern Kenya University",
    "state-province": null,
    domains: ["seku.ac.ke"],
    web_pages: ["http://www.seku.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "St. Pauls University",
    "state-province": null,
    domains: ["spu.ac.ke"],
    web_pages: ["http://www.spu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Strathmore University",
    "state-province": null,
    domains: ["strathmore.edu"],
    web_pages: ["http://www.strathmore.edu/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Technical University of Kenya",
    "state-province": null,
    domains: ["tukenya.ac.ke"],
    web_pages: ["http://www.tukenya.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Technical University of Mombasa",
    "state-province": null,
    domains: ["tum.ac.ke"],
    web_pages: ["http://www.tum.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "University of Eastern Africa, Baraton",
    "state-province": null,
    domains: ["ueab.ac.ke"],
    web_pages: ["http://www.ueab.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "University of Eldoret",
    "state-province": null,
    domains: ["uoeld.ac.ke"],
    web_pages: ["http://www.uoeld.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "University of Nairobi",
    "state-province": null,
    domains: ["uonbi.ac.ke"],
    web_pages: ["http://www.uonbi.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "United States International University",
    "state-province": null,
    domains: ["usiu.ac.ke"],
    web_pages: ["http://www.usiu.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Uzima University College",
    "state-province": null,
    domains: ["uzimauniversity.ac.ke"],
    web_pages: ["http://www.uzimauniversity.ac.ke/"],
  },
  {
    country: "Kenya",
    alpha_two_code: "KE",
    name: "Zetech College",
    "state-province": null,
    domains: ["zetechcollege.com"],
    web_pages: ["http://www.zetechcollege.com/"],
  },
];
module.exports = data;
